### ISSUE TITLE
"unsupported .ter version 3, wanted 2"

### ISSUE THREAD

**Issue by Manwe-fv** [xackery/eqgzi#9]
I'm getting the error "unsupported .ter version 3, wanted 2" when opening certain EQG files with eqgzi 1.8.0 (file is cityofbronze.eqg). Trying to follow the directions in this thread (http://www.eqemulator.org/forums/showthread.php?t=41129) to swap out textures in eqg based zones.

According to Eqemu discord, EQZGI currently only works on OoW or DoN EQG files. Are there any workarounds to using it on later ones?

Thanks!

![error](https://user-images.githubusercontent.com/81694786/178723740-5f36487a-ad90-45e5-a450-896a4a25bc92.PNG)

**Comment by xackery** [comment]
Nope.
The format heavily changed with version 3, and it isn't decoded yet.
I moved my focus to a new project called quail which is my ground up attempt to replace eqgzi, but it still has significant work ahead of it. Once I get the conversion steps done, though, I do plan to add support for 3. Perhaps I'll add it to eqgzi too...

But for now, this is simply a limitation to live with.

**Comment by Manwe-fv** [comment]
Good to know-I look forward to trying out quail. Thanks for all your hard work!
